version: '3.3'
services:
  db:
    container_name: 'local-wordpress-db'
    image: 'mysql:5.7'
    volumes:
      - './data/mysql:/var/lib/mysql'
    ports:
      - 18766:3306
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress

  phpmyadmin:
    container_name: 'admin-tool'
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: wordpress

  wordpress:
    container_name: 'local-wordpress'
    depends_on:
      - db
    image: 'wordpress:latest'
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - "./wordpress:/var/www/html"
      - "./wordpress/wp-content/plugins:/var/www/html/wp-content/plugins"
      - "./wordpress/wp-content/themes:/var/www/html/wp-content/themes"